IDE_HOME := /usr/local/arduino
BOARD := uno
#SKETCH := Blink.ino
#SKETCH := Devices.ino
#SKETCH := Signal.ino
#SKETCH := Philosophers.ino
SKETCH := Channel.ino
CXXFLAGS = -fno-threadsafe-statics
include arduino15.mk
