PROCESSOR_FAMILY := msp430
BOARD := MSP-EXP430FR5739LP
#SKETCH := Blink.ino
#SKETCH := Devices.ino
#SKETCH := Signal.ino
SKETCH := Philosophers.ino
CXXFLAGS = -fno-threadsafe-statics

include energia.mk
